# Utiliser l'image officielle PHP avec Apache
FROM php:8.2-apache

# Copier le fichier index.php dans le dossier web par défaut
COPY index.php /var/www/html/

# Exposer le port 80 du conteneur
EXPOSE 80
